[package]
name = "telegram_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["macros"] }
dotenvy = "0.15.7"
hex = "0.4.3"
hmac = "0.12.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "macros", "time", "bigdecimal"] }
tokio = { version = "1.49.0", features = ["full", "macros", "rt-multi-thread"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5.8"
time = { version = "0.3", features = ["serde","serde-well-known"] }
jsonwebtoken = { version = "10", features = ["use_pem", "rust_crypto"] }
rustls = { version = "0.23", features = ["ring"] }
serde_urlencoded="0.7"
bigdecimal = { version = "0.4", features = ["serde"] }
urlencoding="2"
reqwest = { version = "0.12", features = ["json"] }
